Controllers/AreasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BrtfProject.Data;
using BrtfProject.Models;
using Microsoft.AspNetCore.Authorization;
using BrtfProject.Utilities;

namespace BrtfProject.Controllers
{
    public class AreasController : Controller
    {
        private readonly BrtfDbContext _context;

        public AreasController(BrtfDbContext context)
        {
            _context = context;
        }

        // GET: Areas
       [Authorize]
        public async Task<IActionResult> Index(string SearchString,
            int? page, int? pageSizeID, string actionButton, string sortDirection = "asc", string sortField = "Area")
        {
            string[] sortOptions = new[] { "Area" };

            PopulateDropDownLists();

            ViewData["Filtering"] = "";  //Assume not filtering

            var areas = from r in _context.Areas
                 .AsNoTracking()
                        select r;
            
            if (!String.IsNullOrEmpty(SearchString))
            {
                areas = areas.Where(p => p.AreaName.ToUpper().Contains(SearchString.ToUpper()));
                ViewData["Filtering"] = " show";
            }

            //Before we sort, see if we have called for a change of filtering or sorting
           


            if (sortField == "Area")
            {
                if (sortDirection == "asc")
                {
                    areas = areas
                        .OrderBy(p => p.AreaName);
                }
                else
                {
                    areas = areas
                        .OrderByDescending(p => p.AreaName);
                }
            }

            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted so lets sort!
            {
                if (actionButton != "Filter")//Change of sort is requested
                {
                    if (actionButton == sortField) //Reverse order on same field
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton;//Sort by the button clicked
                }
            }

            //Set sort for next time
            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;

            //Handle Paging
            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID, ControllerName());
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);
            var pagedData = await PaginatedList<Area>.CreateAsync(areas.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);

            //return View(await areas.ToListAsync());
        }
        private void PopulateDropDownLists(Room room = null)
        {
            ViewData["AreaId"] = AreaSelectList(room?.AreaId);
        }
        private SelectList AreaSelectList(int? selectedId)
        {
            return new SelectList(_context.Areas
                .OrderBy(d => d.AreaName), "ID", "AreaName", selectedId);
        }
        private string ControllerName()
        {
            return this.ControllerContext.RouteData.Values["controller"].ToString();
        }
        // GET: Areas/Details/5
       [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var area = await _context.Areas
                .FirstOrDefaultAsync(m => m.ID == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        // GET: Areas/Create
       [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Areas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
       [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,AreaName,description")] Area area)
        {
            if (ModelState.IsValid)
            {
                _context.Add(area);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(area);
        }

        // GET: Areas/Edit/5
       [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var area = await _context.Areas.FindAsync(id);
            if (area == null)
            {
                return NotFound();
            }
            return View(area);
        }

        // POST: Areas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ID,AreaName")] Area area)
        {
            if (id != area.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(area);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AreaExists(area.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(area);
        }

        // GET: Areas/Delete/5
       [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var area = await _context.Areas
                .FirstOrDefaultAsync(m => m.ID == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        // POST: Areas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var area = await _context.Areas.FindAsync(id);
            _context.Areas.Remove(area);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AreaExists(int id)
        {
            return _context.Areas.Any(e => e.ID == id);
        }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BrtfProject.Models;
using Microsoft.AspNetCore.Authorization;
using BrtfProject.Utilities;
using BrtfProject.Data;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Identity.UI.Services;
using BrtfProject.Areas.Identity.Pages.Account;
using Microsoft.AspNetCore.Authentication;

namespace BrtfProject.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        //Specialized controller just used to allow an 
        //Authenticated user to maintain their own  account details.

        private readonly BrtfDbContext _context;
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;
        private readonly ApplicationDbContext _identityContext;

        public UserController(BrtfDbContext context, UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, ILogger<RegisterModel> logger, IEmailSender emailSender, ApplicationDbContext identityContext)
        {
            _context = context;
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            _identityContext = identityContext;
        }

        [BindProperty]
        public InputModel Input { get; set; }
        public string ReturnUrl { get; set; }
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        // GET: UserAccount
        public IActionResult Index()
        {
            return RedirectToAction(nameof(Details));
        }

        // GET: UserAccount/Details/5
        public async Task<IActionResult> Details()
        {

            var user = await _context.Users
               .Where(c => c.Email == User.Identity.Name)
               .FirstOrDefaultAsync();
            if (user == null)
            {
                return RedirectToAction(nameof(Create));
            }

            return View(user);
        }

        // GET: UserAccount/Create
        [Authorize(Roles = "Super-Admin")]
        public async Task<IActionResult> CreateAsync(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            ViewData["ProgramTermId"] = new SelectList(_context.ProgramTerms, "ID", "ProgramInfo");
            ViewData["TermId"] = new SelectList(_context.Terms, "ID", "Code");
            ViewData["UserGroupId"] = new SelectList(_context.UserGroups, "ID", "UserGroupName");
            return View();
        }

        // POST: UserAccount/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Super-Admin")]
        public async Task<IActionResult> Create([Bind("StudentID,FirstName,MiddleName,LastName,ProgramTermId,TermId,UserGroupId,Email,LastLevel")] User user, string returnUrl = null)
        {
            ViewData["ProgramTermId"] = new SelectList(_context.ProgramTerms, "ID", "ProgramInfo");
            ViewData["TermId"] = new SelectList(_context.Terms, "ID", "Code");
            ViewData["UserGroupId"] = new SelectList(_context.UserGroups, "ID", "UserGroupName");
            returnUrl = returnUrl ?? Url.Content("~/");
            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            try
            {
                if (ModelState.IsValid)
                {
                    //Try to add the new user to the DB, if it succeeds then we move on to attempting to create the user's identity
                    //This is to stop the user's account from being a failed creation and then the program making their login anyway.
                    _context.Add(user);
                    var success = await _context.SaveChangesAsync() > 0;
                    
                    if(success != false)
                    {
                        //Here we create the user's new identity using the input.
                        //It's nothing (significantly) different from the regular register page but it is all done in one motion in the user controller.
                        var u = new IdentityUser { UserName = user.Email, Email = user.Email };
                        var result = await _userManager.CreateAsync(u, Input.Password);
                        if (result.Succeeded)
                        {
                            string msg = "Success: account for " + user.Email + " has been created.";
                            _logger.LogInformation(msg);
                            ViewData["msg"] = msg;

                            return RedirectToAction("Index", "UserIdentity");
                            //_logger.LogInformation("User created a new account with password.");

                            //var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                            //code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
                            //var callbackUrl = Url.Page(
                            //    "/Account/ConfirmEmail",
                            //    pageHandler: null,
                            //    values: new { area = "Identity", userId = user.Id, code = code, returnUrl = returnUrl },
                            //    protocol: Request.Scheme);

                            //await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                            //    $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                            //if (_userManager.Options.SignIn.RequireConfirmedAccount)
                            //{
                            //    return RedirectToPage("RegisterConfirmation", new { email = Input.Email, returnUrl = returnUrl });
                            //}
                            //else
                            //{
                            //    await _signInManager.SignInAsync(user, isPersistent: false);
                            //    return LocalRedirect(returnUrl);
                            //}
                        }
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View(user);
        }

        // GET: UserAccount/Edit/5
        public async Task<IActionResult> Edit()
        {
            ViewData["ProgramTermId"] = new SelectList(_context.ProgramTerms, "ID", "ProgramInfo");
            ViewData["TermId"] = new SelectList(_context.Terms, "ID", "Code");
            ViewData["UserGroupId"] = new SelectList(_context.UserGroups, "ID", "UserGroupName");

            var user = await _context.Users
                .Where(c => c.Email == User.Identity.Name)
                .FirstOrDefaultAsync();
            if (user == null)
            {
                return RedirectToAction(nameof(Create));
            }
            return View(user);
        }

        // POST: UserAccount/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            var userToUpdate = await _context.Users
                .FirstOrDefaultAsync(m => m.ID == id);

            if (await TryUpdateModelAsync<User>(userToUpdate, "",
                c => c.FirstName, c => c.MiddleName, c => c.LastName,  c => c.StudentID, c => c.ProgramTermId, c => c.Purge))
            {
                try
                {
                    _context.Update(userToUpdate);
                    await _context.SaveChangesAsync();
                    UpdateUserNameCookie(userToUpdate.FullName);
                    return RedirectToAction(nameof(Details));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(userToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        ModelState.AddModelError("", "Unable to save changes. The record you attempted to edit "
                                + "was modified by another user after you received your values.  You need to go back and try your edit again.");
                    }
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Something went wrong in the database.");
                }
            }
            return View(userToUpdate);

        }

        // GET: UserAccount/Delete/5
        [Authorize(Roles = "Super-Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BrtfProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:white">
    <header class="form-1">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/Mind Tech Workforce.png" height="135" class="img-responsive" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Index">Bookings</a>
                        </li>

                        @if (User.IsInRole("Admin") | User.IsInRole("Super-Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rooms" asp-action="Index">Room</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Look Ups<b class="caret"></b>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Areas" asp-action="Index">Areas</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ProgramTerms" asp-action="Index">Programs</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Terms" asp-action="Index">Terms</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="RoomRules" asp-action="Index">Room Rules</a>
                                    <div class="dropdown-divider"></div>
                                    <div class="dropdown-divider"></div>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserGroups" asp-action="Index">User Groups</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Admin Menu<b class="caret"></b>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">Register New User</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserIdentity" asp-action="Index">View User Details</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">Manage User Roles</a>
                                </div>
                            </li>
                        }


                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div style="background-color:white" class="container">
        <main  role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Brtf <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_PageSizeModal.cshtml
<!-- Modal-->
<div class="modal fade" id="pageSizeModal" tabindex="-1" role="dialog" aria-labelledby="pageSizeModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="pageSizeModalLabel">Set Page Size</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <div class="form-row">
                    <div class="form-group col-md-12">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Page Size: </span>
                            </div>
                            @Html.DropDownList("pageSizeID", null, htmlAttributes: new { @class = "form-control" })
                            <div class="input-group-append">
                                <input type="submit" class="btn btn-primary" value="Set Page Size" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_PagingNavBar.cshtml
<partial name="_PageSizeModal" />
@{
    if (Model.TotalPages == 0)
    {
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">
                <button type="button" title="Click to change page size." data-toggle="modal" data-target="#pageSizeModal" class="btn btn-primary">
                    No Data to Show
                </button>
            </li>
        </ul>
    }
    else if (Model.TotalPages == 1)
    {
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">
                <button type="button" title="Click to change page size." data-toggle="modal" data-target="#pageSizeModal" class="btn btn-primary">
                    Page @Model.PageIndex of @Model.TotalPages
                </button>
            </li>
        </ul>
    }
    else
    {
        var jumpAmount = (Model.TotalPages > 25) ? 10 : 5;
        var prevDisabled = !Model.HasPreviousPage ? "disabled='disabled'" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled='disabled'" : "";
        var stepBack = (Model.PageIndex <= jumpAmount) ? 1 : Model.PageIndex - jumpAmount;
        var stepForward = (Model.PageIndex + jumpAmount > Model.TotalPages) ? Model.TotalPages : Model.PageIndex + jumpAmount;
        <ul class="pagination justify-content-center" style="margin:20px 0">
            <li class="page-item">
                <button type="submit" name="page" value="1" @prevDisabled class="btn page-link">
                    <span aria-hidden="true">&lArr;</span>&nbsp;First
                </button>
            </li>
            <li class="page-item d-none d-md-inline">
                <button type="submit" name="page" value="@(stepBack)" @prevDisabled
                        data-toggle="tooltip" title="Jump Back @(Model.PageIndex-stepBack) Pages" class="btn page-link">
                    <span aria-hidden="true">&lArr;</span>
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @prevDisabled value="@(Model.PageIndex - 1)" class="btn page-link">
                    &nbsp;<span aria-hidden="true">&larr;</span>&nbsp;<span class="d-none d-md-inline">Previous</span>
                </button>
            </li>
            <li class="page-item">
                <button type="button" title="Click to change page size." data-toggle="modal" data-target="#pageSizeModal" class="btn btn-primary">
                    <span class="d-none d-md-inline">Pg. </span>@Model.PageIndex of @Model.TotalPages
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @nextDisabled value="@(Model.PageIndex + 1)" class="btn page-link">
                    <span class="d-none d-md-inline">Next</span>&nbsp;<span aria-hidden="true">&rarr;</span>&nbsp;
                </button>
            </li>
            <li class="page-item d-none d-md-inline">
                <button type="submit" name="page" @nextDisabled value="@(stepForward)" title="Jump Forward @(stepForward-Model.PageIndex) Pages" class="btn page-link">
                    <span aria-hidden="true">&rArr;</span>
                </button>
            </li>
            <li class="page-item">
                <button type="submit" name="page" @nextDisabled value="@(Model.TotalPages)" class="btn page-link">
                    Last&nbsp;<span aria-hidden="true">&rArr;</span>
                </button>
            </li>
        </ul>
    }
}