Controllers/UserIdentityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BrtfProject.Models;
using BrtfProject.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using System.IO;
using Microsoft.AspNetCore.Http.Features;
using BrtfProject.Utilities;
using System.Drawing;

namespace BrtfProject.Controllers
{
    public class UserIdentityController : Controller
    {
        private readonly BrtfDbContext _context;
        private readonly ApplicationDbContext _identityContext;
        private readonly UserManager<IdentityUser> _userManager;

        public UserIdentityController(BrtfDbContext context, ApplicationDbContext identityContext, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _identityContext = identityContext;
            _userManager = userManager;
        }

        // GET: UserIdentity
        [Authorize(Roles = "Admin, Super-Admin")]
        public async Task<IActionResult> Index(string actionButton,string SearchFirstName,string SearchLastName,string SearchProgramTerm,
           string SearchEmail , int? page, int? pageSizeID, string sortField = "User", string sortDirection = "asc")
        {
            string[] sortOptions = new[] { "Student ID", "Full Name", "Email" };

            var users = (from u in _context.Users
                .Include(u => u.ProgramTerm)
                select u).AsNoTracking();

            //if (String.IsNullOrEmpty(SearchStudentID))
            //{
            //    users = users.Where(p => p.StudentID.ToString().Contains(SearchStudentID));
            //}
            if (!String.IsNullOrEmpty(SearchFirstName))
            {
                users = users.Where(p => p.FirstName.ToUpper().Contains(SearchFirstName.ToUpper()));
            }
            if (!String.IsNullOrEmpty(SearchLastName))
            {
                users = users.Where(p => p.LastName.ToUpper().Contains(SearchLastName.ToUpper()));
            }
            if (!String.IsNullOrEmpty(SearchProgramTerm))
            {
                users = users.Where(p => p.ProgramTerm.ProgramInfo.ToUpper().Contains(SearchProgramTerm.ToUpper()));
            }
            if (!String.IsNullOrEmpty(SearchEmail))
            {
                users = users.Where(p => p.Email.ToUpper().Contains(SearchEmail.ToUpper()));
            }





            if (!String.IsNullOrEmpty(actionButton))
            {
                if (sortOptions.Contains(actionButton))
                {
                    if(actionButton == sortField)
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton;
                }
            }

            if (sortField == "Student ID")
            {
                if (sortDirection == "asc")
                {
                    users = users.OrderBy(u => u.StudentID);
                }
                else
                {
                    users = users.OrderByDescending(u => u.StudentID);
                }
            }
            else if (sortField == "Full Name")
            {
                if (sortDirection == "asc")
                {
                    users = users.OrderBy(u => u.FirstName).ThenBy(u => u.LastName).ThenBy(u => u.MiddleName);
                }
                else
                {
                    users = users.OrderByDescending(u => u.FirstName).ThenByDescending(u => u.LastName).ThenByDescending(u => u.MiddleName);
                }
            }
            else
            {
                if (sortDirection == "asc")
                {
                    users = users.OrderBy(u => u.Email);
                }
                else
                {
                    users = users.OrderByDescending(u => u.Email);
                }
            }

            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;


            //Handle Paging
            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID, ControllerName());
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);
            var pagedData = await PaginatedList<User>.CreateAsync(users.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);
        }
        private string ControllerName()
        {
            return this.ControllerContext.RouteData.Values["controller"].ToString();
        }
        //// GET: UserIdentity/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var user = await _context.Users
        //        .FirstOrDefaultAsync(m => m.ID == id);
        //    if (user == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(user);
        //}

        // GET: UserIdentity/Edit/5
        [Authorize(Roles = "Super-Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["ProgramTermId"] = new SelectList(_context.ProgramTerms, "ID", "ProgramInfo");
            ViewData["TermId"] = new SelectList(_context.Terms, "ID", "Code");
            ViewData["UserGroupId"] = new SelectList(_context.UserGroups, "ID", "UserGroupName");

            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: UserIdentity/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Super-Admin")]
        public async Task<IActionResult> Edit(int id, bool Purge)
        {
            var userToUpdate = await _context.Users
                .FirstOrDefaultAsync(u => u.ID == id);

            if (userToUpdate == null)
            {
                return NotFound();
            }

            if(userToUpdate.Purge == false & Purge == true)
            {
                await DeleteIdentityUser(userToUpdate.Email);
            }

            if (await TryUpdateModelAsync<User>(userToUpdate, "", 
                u => u.FirstName, u => u.LastName, u => u.StudentID, u => u.ProgramTermId, u => u.Purge))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(userToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(userToUpdate);
        }

        private async Task DeleteIdentityUser(string Email)
        {
            var userToDelete = await _identityContext.Users.Where(u => u.Email == Email).FirstOrDefaultAsync();
            if(userToDelete != null)
            {
                _identityContext.Users.Remove(userToDelete);
                await _identityContext.SaveChangesAsync();
            }
        }
        [HttpPost]

        [Authorize(Roles = "Super-Admin")]
        public async Task<IActionResult> InsertFromExcel(IFormFile theExcel)
        {
            ExcelPackage excel;
            if(theExcel != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await theExcel.CopyToAsync(memoryStream);
                    excel = new ExcelPackage(memoryStream);
                }
                var workSheet = excel.Workbook.Worksheets[0];
                var start = workSheet.Dimension.Start;
                var end = workSheet.Dimension.End;

                //Start a new list to hold imported objects
                List<User> users = new List<User>();
                List<ProgramTerm> pts = new List<ProgramTerm>();
                List<Term> ts = new List<Term>();

                for (int row = start.Row; row <= end.Row; row++)
                {
                    //Check if columns 1, 2, 4, 5, 6, 7, 8 and 10 are empty
                    //These columns are important as they are required fields
                    //If columns are empty, the program skips to the next row
                    if (workSheet.Cells[row, 1].Text != "" && workSheet.Cells[row, 2].Text != "" && workSheet.Cells[row, 4].Text != "" && workSheet.Cells[row, 5].Text != "" && workSheet.Cells[row, 6].Text != "" && workSheet.Cells[row, 7].Text != "" && workSheet.Cells[row, 8].Text != "" && workSheet.Cells[row, 9].Text != "" && workSheet.Cells[row, 10].Text != "")
                    {
                        if (workSheet.Cells[row, 1].Text.Contains("ID") | workSheet.Cells[row, 2].Text.Contains("Name") |
                            workSheet.Cells[row, 4].Text.Contains("Name") | workSheet.Cells[row, 7].Text.Contains("Email") | 
                            workSheet.Cells[row, 10].Text.Contains("Term"))
                        {
                            continue;
                        }
                        else
                        {
                            //Create a string for the Program Term spot
                            //Take the Program Term and find it using firstordefaultasync
                            //Then assign that Program ID to the user

Views/UserIdentity/Edit.cshtml
@model BrtfProject.Models.User

@{
    ViewData["Title"] = "Edit User";
}

<h4>Account Details for @Model.FullName (@Model.Email)</h4>
<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
    <input type="hidden" asp-for="Email" />
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="StudentID" class="control-label"></label>
                <a class="require">*</a>
                <input asp-for="StudentID" class="form-control" />
                <span asp-validation-for="StudentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <a class="require">*</a>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MiddleName" class="control-label"></label>
                <input asp-for="MiddleName" class="form-control" />
                <span asp-validation-for="MiddleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <a class="require">*</a>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TermLevel" class="control-label"></label>
                <a class="require">*</a>
                <select asp-for="TermLevel" style="width:350px; height: 35px;">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="ProgramTermId" class="control-label"></label>
                <a class="require">*</a>
                <select asp-for="ProgramTermId" class="form-control" asp-items="ViewBag.ProgramTermId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Term" class="control-label"></label>
                <a class="require">*</a>
                <select asp-for="TermId" class="form-control" asp-items="ViewBag.TermId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UserGroup" class="control-label"></label>
                <a class="require">*</a>
                <select asp-for="UserGroupId" class="form-control" asp-items="ViewBag.UserGroupId"></select>
            </div>
            @{
                if (Model.Email != User.Identity.Name)
                {
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Purge" /> @Html.DisplayNameFor(model => model.Purge)
                        </label>
                        @{
                            if (Model.Purge == false)
                            {
                                <div><strong>If you select the purge option, their login will be removed from the system. If you ever want to add them back, you must register them again with the same email.</strong></div>
                            }
                            else
                            {
                                <div><strong>If you deselect this, you will need to register the user under the same email again for them to be able to login.</strong></div>
                            }
                        }
                    </div>
                }
            }
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserIdentity/Index.cshtml
@model IEnumerable<BrtfProject.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h2>User Information</h2>

<p>
    <a class="btn btn-primary" asp-area="" asp-controller="User" asp-action="Create">Register New User</a>
</p>
<br />
<div class="card mb-sm-3">
    <div class="form-horizontal">
        <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" id="filterToggle" data-target="#collapseTemplate" aria-expanded="false" aria-controls="collapseTemplate">
            Upload Data
        </button>
        <a asp-action="DownloadTemplate" class="btn btn-info float-right">Download Template for Data</a>
        <div class="collapse @(ViewData["Upload"])" id="collapseTemplate">
            <h4 class="card-header" id="UserImport">Import Users</h4>
            <div class="card-body">
                <br />
                <form asp-action="InsertFromExcel" asp-controller="UserIdentity" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label class="control-label">Upload Excel File:</label>
                        <input type="file" class="" name="theExcel" /><br />
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <input type="submit" value="Upload Data" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
   
</div>
<form asp-action="Index" method="get">
    <input type="hidden" name="sortDirection" value="@ViewData["sortDirection"]" />
    <input type="hidden" name="sortField" value="@ViewData["sortField"]" />
    <div class="form-horizontal">
        <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" id="filterToggle" data-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter">
            Filter/Search
        </button>
        <div class="collapse @(ViewData["Filtering"])" id="collapseFilter">
            <div class="card card-body bg-light">
                <div class="row">
                    @*<div class="form-group col-md-4">
                        <label class="control-label">search student id:</label>
                        @html.textbox("searchstudentid", null, new { @class = "form-control" })
                    </div>*@
                    <div class="form-group col-md-4">
                        <label class="control-label">Search First Name:</label>
                        @Html.TextBox("SearchFirstName", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label">Search Last Name:</label>
                        @Html.TextBox("SearchLastName", null, new { @class = "form-control" })
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="control-label">Search Program Term:</label>
                        @Html.TextBox("SearchProgramTerm", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label">Search By Email:</label>
                        @Html.TextBox("SearchEmail", null, new { @class = "form-control" })
                    </div>

                    <div class="form-group col-md-8 align-self-end">
                        <input type="submit" name="actionButton" value="Filter" class="btn btn-outline-primary" />
                        <a asp-action="Index" class="btn btn-outline-dark">Clear</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <input type="submit" name="actionButton" value="Student ID" class="btn btn-link" />
                </th>
                <th>
                    <input type="submit" name="actionButton" value="Full Name" class="btn btn-link" />
                </th>
                <th>
                    <input type="submit" disabled="disabled" name="actionButton" value="Program Term" class="btn btn-link" />
                </th>
                <th>
                    <input type="submit" name="actionButton" value="Email" class="btn btn-link" />
                </th>
                <th>
                    <input type="submit" disabled="disabled" name="actionButton" value="Purge" class="btn btn-link" />
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StudentID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProgramTerm.ProgramInfo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Purge)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit |</a>
                        <a asp-controller="User" asp-action="Delete" asp-route-id="@item.ID"> Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <partial name="_PagingNavBar" />
</form>